# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
title: Mardené de Villiers
name: Sales Support Technician
email: mcdevilliers18@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  dieniemdv
linkedin_username: mardené-de-villiers

# About Section
# about_title: About Me 
about_profile_image: images/image.png
about_content: | # this will include new lines to allow paragraphs
  Final year BSc IT student studying at the North-West University. Government and International working experience as a Port Meteorological Officer at the South African Weather Service. Currently work as a Sales Support Technician at the largest polyethylene and polypropylene company in the southern hemisphere.

content:
  - title: Skills # Title for the section
    layout: text
    content: | # this will include new lines to allow paragraphs
          - <mark>Programming Languages:</mark> Python, C++, C#
          - <mark>Databases:</mark> MySQL
          - <mark>CRM:</mark> SalesForce
          - <mark>ERP:</mark> Abas
          - <mark>Tools & Methods:</mark> Git, Agile
          - <mark>Administration:</mark> logistic, data collection, management

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Polymaster
        link: https://www.polymaster.com.au/
        # link_text: polymaster.com.au
        sub_title: Sales Support Technician
        caption: January 2024 – Current
        quote: >
          Game-Changing Innovation, Focus on the Customer, Don’t Forget to Enjoy the Journey
        description: | # this will include new lines to allow paragraphs
            Abas ERP, Sales Order Processing, Invoice Processing, Salesforce.com, Smartsheet, Salesforce CPQ, Customer Service

      - layout: left
        title: South African Weather Service
        link: https://www.weathersa.co.za/
        # link_text: weathersa.co.za
        sub_title: Port Meteorological Officer
        caption: May 2015 – November 2023
        quote: >
          Authoritative voice for weather and climate forecasting in South Africa
        description: | # this will include new lines to allow paragraphs
            - International panel experience: Under the Global Ocean Observing System (GOOS) panels include Executive committee member of Ship Observation Team, Chair of Task Team on Recruitment, Promotion and Training under Voluntary Observing Ship Scheme and South African national representative on the Ship Observation Team.
            - Chief Scientist and Group Leader experience on board the SA Agulhas II Research Vessel: Marion Island Relief Voyage (2016), South African National Antarctic Expedition Base Relief Voyage (2016/2017), Winter Research Cruise (2017 & 2019), Spring Research Cruise (2019), Gough Island and Tristan da Cunha Relief Voyage (2021), SeaMester (2022)

      - layout: left
        title: South African Weather Service
        link: https://www.weathersa.co.za/
        # link_text: weathersa.co.za
        sub_title: Meteorological Technician
        caption: April 2014 – April 2015
        quote: >
          Authoritative voice for weather and climate forecasting in South Africa
        description: | # this will include new lines to allow paragraphs
            - Aviation Weather Observations, Special Weather Reports, Weather Station Inspection and Maintenance

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: North-West University
        caption: 2020-2024 (Distance Learning)
        sub_title: Bachelor of Science in Information Technology
        quote: >
          We offer people a place in the world. Academically, students benefit from great choice and flexibility, enabling them to fulfill their potential and start preparing for their careers. 

      - layout: left
        title: South African Weather Service
        caption: February 2013 – November 2013
        sub_title: National Certificate Weather Observations
        quote: >
          Graduates conform to all the requirements according to the definition of the World Meteorological Organization (WMO) Technical Regulations for Weather Observations

      - layout: left
        title: RMIT University
        caption: August 2024 - October 2024
        sub_title: SalesForce Administrator
        quote: >
          Becoming a Salesforce Administrator is the first step on a career pathway that may lead to roles as a well-rounded CRM professional

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in programming and leadership some of my other interests and hobbies are:
      - Lawn Bowls
      - Soccer
      - Gaming
      - Social

  - content:
    layout: centre
    (images/handshake.jpg "handshake")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
